name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

  workflow_dispatch:
    inputs:
      env:
        required: true
        type: choice
        description: Select environment
        options:
          - QA
          - DEV
      tags:
        required: false
        type: string
        description: Enter tags to filter tests (comma-separated)


jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      TEST_ENV: ${{ github.event.inputs.env }}
      TEST_TAGS: ${{ github.event.inputs.tags }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: |
        # If TEST_TAGS is provided, convert comma-separated list to a regex OR (a|b)
        if [ -n "${TEST_TAGS}" ]; then
          GREP=$(echo "${TEST_TAGS}" | sed 's/,/|/g')
          echo "Running tests with grep=${GREP}"
          npx playwright test --grep "${GREP}" --reporter=html
        else
          echo "Running all tests (no tags provided)"
          npx playwright test --reporter=html
        fi
    - name: Upload Playwright HTML report
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Upload Playwright traces
      if: failure()   # ✅ only upload traces if tests fail
      uses: actions/upload-artifact@v4
      with:
        name: playwright-traces
        path: test-results/**/*.zip
        retention-days: 7
        
  view-report:
      needs: test   # ✅ run after tests
      runs-on: ubuntu-latest
      steps:
        - uses: actions/download-artifact@v4
          with:
            name: playwright-report
            path: playwright-report
        - name: Publish Report URL
          run: |
            echo "### Playwright Report" >> $GITHUB_STEP_SUMMARY
            echo "You can download and open the report locally:" >> $GITHUB_STEP_SUMMARY
            echo "- Artifact: [Playwright Report](./playwright-report/index.html)" >> $GITHUB_STEP_SUMMARY
